---
molecule_exceptions:
  - variation: "ubi8"
    reason: "No chrony/ntp package in default repositories"
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "fedora35"
      - "fedora36"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
