---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Molecule tests sometime fail with chronyd in the container
    # so we disable it for testing
    ntp_state: stopped
    ntp_enabled: false
  roles:
    - role: "ansible-role-ntp"
