---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    ntp_daemon_map:
      CentOS:
        "7": "ntpd"
        "8": "chronyd"
        "9": "chronyd"
      RedHat:
        "7": "ntpd"
        "8": "chronyd"
        "9": "chronyd"
      Fedora: "chronyd"
      Rocky:
        "8": "chronyd"
      AlmaLinux:
        "8": "chronyd"
      Amazon:
        "2": "ntpd"
      Debian: "ntp"
      Ubuntu: "ntp"

    ntp_daemon: "{{ ntp_daemon_map[ansible_distribution][ansible_distribution_major_version] | default(ntp_daemon_map[ansible_distribution]) }}"

    ntp_package_map:
      CentOS:
        "7": "ntp"
        "8": "chrony"
        "9": "chrony"
      RedHat:
        "7": "ntp"
        "8": "chrony"
        "9": "chrony"
      Fedora: "chrony"
      Rocky:
        "8": "chrony"
      AlmaLinux:
        "8": "chrony"
      Amazon:
        "2": "ntp"
      Debian: "ntp"
      Ubuntu: "ntp"

    ntp_package: "{{ ntp_package_map[ansible_distribution][ansible_distribution_major_version] | default(ntp_package_map[ansible_distribution]) }}"

    ntp_config_template_map:
      CentOS:
        "7": "ntp.conf.j2"
        "8": "chrony.conf.j2"
        "9": "chrony.conf.j2"
      RedHat:
        "7": "ntp.conf.j2"
        "8": "chrony.conf.j2"
        "9": "chrony.conf.j2"
      Fedora: "chrony.conf.j2"
      Rocky:
        "8": "chrony.conf.j2"
      AlmaLinux:
        "8": "chrony.conf.j2"
      Amazon:
        "2": "ntp.conf.j2"
      Debian: "ntp.conf.j2"
      Ubuntu: "ntp.conf.j2"

    ntp_config_template: "{{ ntp_config_template_map[ansible_distribution][ansible_distribution_major_version] | default(ntp_config_template_map[ansible_distribution]) }}"

    ntp_config_dest_map:
      CentOS:
        "7": "/etc/ntp.conf"
        "8": "/etc/chrony.conf"
        "9": "/etc/chrony.conf"
      RedHat:
        "7": "/etc/ntp.conf"
        "8": "/etc/chrony.conf"
        "9": "/etc/chrony.conf"
      Fedora: "/etc/chrony.conf"
      Rocky:
        "8": "/etc/chrony.conf"
      AlmaLinux:
        "8": "/etc/chrony.conf"
      Amazon:
        "2": "/etc/ntp.conf"
      Debian: "/etc/ntp.conf"
      Ubuntu: "/etc/ntp.conf"

    ntp_config_dest: "{{ ntp_config_dest_map[ansible_distribution][ansible_distribution_major_version] | default(ntp_config_dest_map[ansible_distribution]) }}"

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check ntp package is installed
      ansible.builtin.package:
        name: "{{ ntp_package }}"
        state: present
      register: package_installed
      failed_when: (package_installed is changed) or (package_installed is failed)

    - name: check ntp/chrony.conf file
      lineinfile:
        name: '{{ ntp_config_dest }}'
        line: '# Ansible managed: Do NOT edit this file manually!'
        state: present
        owner: root
        group: root
        mode: '0644'
      check_mode: true
      register: molecule_repository
      failed_when: (molecule_repository is changed) or (molecule_repository is failed)

    - name: check ntp daemon
      service:
        name: "{{ ntp_daemon }}"
        state: started
        enabled: true
      check_mode: true
      register: molecule_service
      failed_when: (molecule_service is changed) or (molecule_service is failed)
